Private/poonam/vmha sync
platform9/pf9-ha pull request #20
Opened 2022-09-23 04:01 UTC by poonam-agarwal28

2022-09-30 06:29 UTC, poojaghumre requested changes

2022-09-30 06:29 UTC, poojaghumre commented on hamgr/hamgr/db/api.py
> +        mdb_session.close()
nit: pleas add new line after this func

2022-09-30 06:29 UTC, poojaghumre commented on hamgr/hamgr/db/api.py
> +            result = query.first()
lets log a warning if there are more than 1 hosts here?

2022-09-30 06:29 UTC, poojaghumre commented on hamgr/hamgr/providers/nova.py
> +
nit: remove extra line

2022-10-03 04:04 UTC, poonam-agarwal28 commented on hamgr/hamgr/db/api.py
> +            result = query.first()
That shouldnt be a possibility I presume ? This function is only checking if the host is already apart of Masakari Database and will add only when it doesnt find an existing entry

2022-10-03 04:04 UTC, poonam-agarwal28 commented on hamgr/hamgr/providers/nova.py
> +
OK will do

2022-10-03 13:33 UTC, merged